# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule: 
    - cron: "0 0 * * *"
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Using Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn start
      - env:
          INSTAGRAM_ACCESS_TOKEN: ${{secrets.INSTAGRAM_ACCESS_TOKEN}}
          INSTAGRAM_ID: ${{secrets.INSTAGRAM_ID}}
          CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
          CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
          NETLIFY_WEBHOOK: ${{secrets.NETLIFY_WEBHOOK}}
